# https://www.mkdocs.org/user-guide/configuration/
# https://www.mkdocs.org/user-guide/writing-your-docs/
# https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/writing-your-docs/
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/styling-your-docs/
# https://example-mkdocs-basic.readthedocs.io/en/latest/
# https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml
# mkdocs.yml

site_name: Catesta - tbd
# site_url:
repo_url: https://github.com/techthoughts2/Catesta
# repo_name:
# edit_uri: edit/main/docs/
# edit_uri_template:
site_description: Catesta read the docs deployment # meta tag to the generated HTML header
site_author: Jake # meta tag to the generated HTML header
copyright: "2023 copyright"
# remote_branch:
# remote_name:
# docs_dir: docs
# site_dir:
# extra_css:
# extra_javascript:
# extra_templates:
# extra:
# theme: readthedocs
theme:
  name: readthedocs
  # custom_dir: overrides
  # favicon: assets/favicon.png
  # font:
  #   text: Work Sans
  logo: assets/CatestaIcon.png
  name: material
  palette:
    primary: teal
# theme:
#     name: readthedocs
#     locale: en
    # custom_dir: my_theme_customizations/
    # static_templates:
    #     - sitemap.html
    # include_sidebar: true
nav:
  - Home: index.md
  - Change Log: CHANGELOG.md
  - Functions:
    - New-ModuleProject: New-ModuleProject.md
    - New-VaultProject: New-VaultProject.md


#  -------------------------------------------------------------------------------------------
# site_name:
# site_url:
# repo_url:
# repo_name:
# edit_uri:
# edit_uri_template:
# site_description:
# site_author:
# copyright:
# remote_branch:
# remote_name:
# docs_dir:
# site_dir:
# extra_css:
# extra_javascript:
# extra_templates:
# extra:
  # version: 1.0
# theme:
#     name: mkdocs
#     locale: en
#     custom_dir: my_theme_customizations/
#     static_templates:
#         - sitemap.html
#     include_sidebar: false
# Navigation sub-sections can be created by listing related pages together under a section title. For example:
# nav:
#     - Home: 'index.md'
#     - 'User Guide':
#         - 'Writing your docs': 'writing-your-docs.md'
#         - 'Styling your docs': 'styling-your-docs.md'
#     - About:
#         - 'License': 'license.md'
#         - 'Release Notes': 'release-notes.md'
# -------------------------------------------------------------------------------------------


# site_name: Convert - PowerShell Module for object conversions
# repo_url: https://github.com/austoonz/Convert
# site_author: Andrew Pearce
# edit_uri: edit/master/docs/
# theme: readthedocs
# copyright: "Convert is licensed under the <a href='https://github.com/austoonz/Convert/blob/master/LICENSE'>MIT license"
# pages:
#   - Home: index.md
#   - Change Log: CHANGELOG.md
#   - Functions:
#     - ConvertFrom-Base64: functions/ConvertFrom-Base64.md
#     - ConvertFrom-Base64ToByteArray: functions/ConvertFrom-Base64ToByteArray.md
