# https://www.mkdocs.org/user-guide/configuration/
# https://www.mkdocs.org/user-guide/writing-your-docs/
# https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/writing-your-docs/
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/styling-your-docs/
# https://example-mkdocs-basic.readthedocs.io/en/latest/
# https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml
# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# mkdocs.yml

site_name: <%=$PLASTER_PARAM_ModuleName%>
# site_url:
# repo_url:
# repo_name:
# edit_uri: edit/main/docs/
# edit_uri_template:
site_description: <%=$PLASTER_PARAM_Description%> # meta tag to the generated HTML header
site_author: <%=$PLASTER_PARAM_FN%> # meta tag to the generated HTML header
# copyright:
# remote_branch:
# remote_name:
# docs_dir: docs
# site_dir:
# extra_css:
# extra_javascript:
# markdown_extensions:
  # Python Markdown
  # - admonition
  # - toc:
  #     permalink: true
  # code highlighting
  # - pymdownx.highlight:
  #     use_pygments: true
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.inlinehilite
  # - pymdownx.snippets
  # - pymdownx.superfences

# extra_templates:
# extra:
theme:
  name: material
  # language: en
  # custom_dir: overrides
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.path
  # favicon:
  # icon:
  #   repo:
  # font:
  #   text: Work Sans
  # logo:
  # palette:
  #   primary: teal
  # palette:
  #   # Palette toggle for light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: light blue
  #     accent: pink
  #     toggle:
  #       icon: material/brightness-7
  #       name: Switch to dark mode

    # # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: indigo
    #   accent: pink
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
nav:
  - Home: index.md
  - Change Log: CHANGELOG.md
  # - Functions:
  #   - Function1: functions/function1.md
