# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Catesta-MacOS
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Display the path
      shell: pwsh
      run: echo ${env:GITHUB_WORKSPACE}
    - name: Version Display
      shell: pwsh
      run: $PSVersionTable
    - name: Bootstrap
      shell: pwsh
      run: ./actions_bootstrap.ps1
    - name: Test and Build
      shell: pwsh
      run: Invoke-Build -File .\src\Catesta.build.ps1