# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell
# https://github.com/actions/upload-artifact#where-does-the-upload-go
name: Catesta-MacOS
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
    branches:
      - '!doctesting' # excludes doctesting branch
jobs:
  test:
    name: Run Tests
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Display the path
      shell: pwsh
      run: echo ${env:GITHUB_WORKSPACE}
    - name: Version Display
      shell: pwsh
      run: $PSVersionTable
    - name: Bootstrap
      shell: pwsh
      run: ./actions_bootstrap.ps1
    - name: Test and Build
      shell: pwsh
      run: Invoke-Build -File .\src\Catesta.build.ps1
    - name: Upload pester results
      uses: actions/upload-artifact@v2
      with:
        name: pester-results
        path: ./src/Artifacts/testOutput
        if-no-files-found: warn
    - name: Upload zip module archive build
      uses: actions/upload-artifact@v2
      with:
        name: zip-archive
        path: ./src/Archive
        if-no-files-found: warn
